image:
  tag: release

ingress:
  host: prism-web.ebus.swaws

env:
  API_URL: "https://develop-prism-api.ebus.swaws"
  WEB_URL: "https://prism-web.ebus.swaws"

service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:iam::133667126030:server-certificate/prism.sherwin-williams.com'
