image:
  tag: release

ingress:
  host: prism-web.ebus.swaws

env:
  API_URL: "https://prism-api.sherwin-williams.com"
  WEB_URL: "https://prism.sherwin-williams.com"

service:
  type: LoadBalancer
  port: 80
  httpsPort: 443
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:iam::133667126030:server-certificate/prism.sherwin-williams.com2021'
