name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: sw-ubuntu-k8s
    env:
      NODE_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

#      - name: Unit Tests1
#        run: yarn test

      - name: Build
        run: yarn run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync to S3
        run: aws s3 sync ./packages/facets/dist s3://sw-prism-web/gh-action-test/develop/